import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  TextInput,
  StyleSheet,
  TouchableOpacity,
  ScrollView,
  Alert,
  Platform,
  ActivityIndicator,
} from 'react-native';
import { moderateScale } from './utils/scalingUtils';
import { getToken } from '../services/authStorage';
import { Picker } from '@react-native-picker/picker';
import DateTimePicker, { DateTimePickerEvent } from '@react-native-community/datetimepicker';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { RouteProp } from '@react-navigation/native';
import { useToggleStore } from '../stores/useToggleStore';

type RootStackParamList = {
  AddUser: undefined;
};

type AddUserPageNavigationProp = NativeStackNavigationProp<RootStackParamList, 'AddUser'>;
type AddUserPageRouteProp = RouteProp<RootStackParamList, 'AddUser'>;

interface Props {
  navigation: AddUserPageNavigationProp;
  route: AddUserPageRouteProp;
}

export const AddUserPage: React.FC<Props> = ({ navigation }) => {
  const { isEnglish } = useToggleStore();

  const [userid, setUserId] = useState<number>(0); // autogenerated user ID
  const [name, setName] = useState<string>('');
  const [username, setUsername] = useState<string>('');
  const [email, setEmail] = useState<string>('');
  const [password, setPassword] = useState<string>('');
  const [userrole, setUserRole] = useState<number>(3); // default Customer
  const [phone, setPhone] = useState<string>('');
  const [dateOfBirth, setDateOfBirth] = useState<Date>(new Date());
  const [showDatePicker, setShowDatePicker] = useState<boolean>(false);
  const [gender, setGender] = useState<'Male' | 'Female' | 'Other'>('Male');
  const [loading, setLoading] = useState<boolean>(false);

  // Generate a random userid on component mount
  useEffect(() => {
    const min = 9999999999;
    const max = 9999999999999;
    const randomUserId = Math.floor(Math.random() * (max - min + 1)) + min;
    setUserId(randomUserId);
  }, []);

  const validateInputs = () => {
    if (!name.trim() || !username.trim() || !email.trim() || !password || !phone.trim()) {
      Alert.alert(isEnglish ? 'Validation Error' : 'சரிபார்ப்பு பிழை', isEnglish ? 'All fields are required.' : 'அனைத்து புலங்களும் நிரப்பப்பட வேண்டும்.');
      return false;
    }
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      Alert.alert(isEnglish ? 'Validation Error' : 'சரிபார்ப்பு பிழை', isEnglish ? 'Invalid email format.' : 'தவறான மின்னஞ்சல் வடிவம்.');
      return false;
    }
    if (!/^\d{10}$/.test(phone)) {
      Alert.alert(isEnglish ? 'Validation Error' : 'சரிபார்ப்பு பிழை', isEnglish ? 'Phone must be 10 digits.' : 'தொலைபேசி எண் 10 இலக்கங்கள் இருக்க வேண்டும்.');
      return false;
    }
    return true;
  };

  const handleAddUser = async () => {
    if (!validateInputs()) return;

    try {
      setLoading(true);
      const token = await getToken();
      if (!token) {
        setLoading(false);
        return Alert.alert(isEnglish ? 'Error' : 'பிழை', isEnglish ? 'User not authenticated' : 'பயனர் அங்கீகரிக்கப்படவில்லை');
      }

      const payload = {
        userid,
        name,
        username,
        email,
        password,
        userrole,
        phone,
        balance: 0,
        advance: 0,
        dateOfBirth: dateOfBirth.toISOString().split('T')[0],
        gender,
        statements: [] as any[],
      };

      const response = await fetch('https://bricksyncback.onrender.com/api/users', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify(payload),
      });

      const resData = await response.json();
      if (!response.ok) {
        console.error('Server error:', resData);
        throw new Error(resData.message || (isEnglish ? 'Failed to add user' : 'பயனரை சேர்க்க முடியவில்லை'));
      }

      Alert.alert(isEnglish ? 'Success' : 'வெற்றி', isEnglish ? 'User added successfully' : 'பயனர் வெற்றிகரமாக சேர்க்கப்பட்டது');
      navigation.goBack();
    } catch (err: any) {
      console.error('❌ Add user failed:', err);
      Alert.alert(isEnglish ? 'Error' : 'பிழை', err.message || (isEnglish ? 'Failed to add user' : 'பயனரை சேர்க்க முடியவில்லை'));
    } finally {
      setLoading(false);
    }
  };

  const handleDateChange = (event: DateTimePickerEvent, selectedDate?: Date) => {
    setShowDatePicker(Platform.OS === 'ios');
    if (selectedDate) setDateOfBirth(selectedDate);
  };

  return (
    <ScrollView contentContainerStyle={styles.container}>
      <Text style={styles.title}>{isEnglish ? 'Add New User' : 'புதிய பயனரை சேர்க்கவும்'}</Text>

      <TextInput
        style={styles.input}
        placeholder={isEnglish ? 'Name' : 'பெயர்'}
        placeholderTextColor="#999"
        value={name}
        onChangeText={setName}
      />

      <TextInput
        style={styles.input}
        placeholder={isEnglish ? 'Username' : 'பயனர் பெயர்'}
        placeholderTextColor="#999"
        value={username}
        onChangeText={setUsername}
      />

      <TextInput
        style={styles.input}
        placeholder={isEnglish ? 'Email' : 'மின்னஞ்சல்'}
        placeholderTextColor="#999"
        keyboardType="email-address"
        value={email}
        onChangeText={setEmail}
      />

      <TextInput
        style={styles.input}
        placeholder={isEnglish ? 'Password' : 'கடவுச்சொல்'}
        placeholderTextColor="#999"
        secureTextEntry
        value={password}
        onChangeText={setPassword}
      />

      <Text style={styles.label}>{isEnglish ? 'User Role' : 'பயனர் வகை'}</Text>
      <View style={styles.pickerContainer}>
        <Picker selectedValue={userrole} onValueChange={(itemValue) => setUserRole(itemValue)}>
          <Picker.Item label={isEnglish ? 'Customer' : 'வாடிக்கையாளர்'} value={3} />
          <Picker.Item label={isEnglish ? 'Driver' : 'ஓட்டுநர்'} value={2} />
          <Picker.Item label={isEnglish ? 'Admin' : 'நிர்வாகி'} value={1} />
        </Picker>
      </View>

      <TextInput
        style={styles.input}
        placeholder={isEnglish ? 'Phone' : 'தொலைபேசி'}
        placeholderTextColor="#999"
        keyboardType="phone-pad"
        value={phone}
        onChangeText={setPhone}
      />

      <Text style={styles.label}>{isEnglish ? 'Date of Birth' : 'பிறந்த தேதி'}</Text>
      <TouchableOpacity style={styles.datePickerButton} onPress={() => setShowDatePicker(true)}>
        <Text style={styles.datePickerText}>{dateOfBirth.toISOString().split('T')[0]}</Text>
      </TouchableOpacity>
      {showDatePicker && (
        <DateTimePicker
          value={dateOfBirth}
          mode="date"
          display="default"
          onChange={handleDateChange}
          maximumDate={new Date()}
        />
      )}

      <Text style={styles.label}>{isEnglish ? 'Gender' : 'பாலினம்'}</Text>
      <View style={styles.pickerContainer}>
        <Picker
          selectedValue={gender}
          onValueChange={(value) => setGender(value as 'Male' | 'Female' | 'Other')}
        >
          <Picker.Item label={isEnglish ? 'Male' : 'ஆண்'} value="Male" />
          <Picker.Item label={isEnglish ? 'Female' : 'பெண்'} value="Female" />
          <Picker.Item label={isEnglish ? 'Other' : 'மற்றவை'} value="Other" />
        </Picker>
      </View>

      <TouchableOpacity
        style={[styles.button, loading && { opacity: 0.7 }]}
        onPress={handleAddUser}
        disabled={loading}
      >
        {loading ? (
          <ActivityIndicator color="#fff" />
        ) : (
          <Text style={styles.buttonText}>{isEnglish ? 'Add User' : 'பயனரை சேர்க்கவும்'}</Text>
        )}
      </TouchableOpacity>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    padding: moderateScale(16),
    backgroundColor: '#F9F9F9',
    marginTop:moderateScale(24)
  },
  title: {
    fontSize: moderateScale(24),
    fontWeight: 'bold',
    marginBottom: moderateScale(24),
    textAlign: 'center',
    color: '#000',
  },
  label: {
    fontSize: moderateScale(16),
    fontWeight: 'bold',
    marginBottom: moderateScale(8),
    color: '#000',
  },
  input: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: moderateScale(8),
    padding: moderateScale(12),
    marginBottom: moderateScale(16),
    backgroundColor: '#fff',
    color: '#000',
  },
  pickerContainer: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: moderateScale(8),
    marginBottom: moderateScale(16),
    backgroundColor: '#fff',
  },
  datePickerButton: {
    padding: moderateScale(12),
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: moderateScale(8),
    marginBottom: moderateScale(16),
    backgroundColor: '#fff',
  },
  datePickerText: {
    color: '#000',
  },
  button: {
    backgroundColor: '#007bff',
    padding: moderateScale(16),
    borderRadius: moderateScale(8),
    alignItems: 'center',
    marginTop: moderateScale(16),
  },
  buttonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: moderateScale(16),
  },
});
